In [ ]:
catalog = dbutils.widgets.get("catalog")

spark.sql(f"""
    CREATE CATALOG IF NOT EXISTS {catalog};
""")

In [4]:
spark.sql(f"CREATE SCHEMA IF NOT EXISTS {catalog}.landing")
spark.sql(f"CREATE SCHEMA IF NOT EXISTS {catalog}.bronze")
spark.sql(f"CREATE SCHEMA IF NOT EXISTS {catalog}.silver")
spark.sql(f"CREATE SCHEMA IF NOT EXISTS {catalog}.gold")

DataFrame[]

In [ ]:
spark.sql(f"CREATE VOLUME IF NOT EXISTS {catalog}.landing.yellow_trip_data")
spark.sql(f"CREATE VOLUME IF NOT EXISTS {catalog}.landing.lookups")

DataFrame[]