### Catalog Setup Script

This notebook is intended to setup NYC Taxi project data structure - catalogs, schemas and volumes.
It should be executed manually on Databricks Workspace by privileged user with Workspace access.

If catalog is created on Production, ownership for catalog and schemas should be assigned to dedicated user group - `nyctaxi_contributors` with Data Editor permissions setup on catalog level. Permissions on schema level should be inherited.

In [ ]:
catalog = "nyctaxi_dev"  # replace with catalog name

spark.sql(f"""
    CREATE CATALOG IF NOT EXISTS {catalog};
""")

In [4]:
spark.sql(f"CREATE SCHEMA IF NOT EXISTS {catalog}.landing")
spark.sql(f"CREATE SCHEMA IF NOT EXISTS {catalog}.bronze")
spark.sql(f"CREATE SCHEMA IF NOT EXISTS {catalog}.silver")
spark.sql(f"CREATE SCHEMA IF NOT EXISTS {catalog}.gold")

DataFrame[]

In [ ]:
spark.sql(f"CREATE VOLUME IF NOT EXISTS {catalog}.landing.yellow_trip_data")
spark.sql(f"CREATE VOLUME IF NOT EXISTS {catalog}.landing.lookups")

DataFrame[]