In [1]:
print("Hello! Let's learn about Databricks Declarative Automation Bundles.")

Hello! Let's learn about Databricks Declarative Automation Bundles.

In [1]:
spark.sql("SHOW CATALOGS").show()

+-------------+
|      catalog|
+-------------+
| citibike_dev|
|citibike_prod|
|citibike_test|
|  nyctaxi_dev|
|          raw|
|      samples|
|       system|
|    workspace|
+-------------+

In [3]:
spark.sql("""
    USE SCHEMA sql_challenges
""")
spark.sql("""
    SHOW TABLES
""")

DataFrame[database: string, tableName: string, isTemporary: boolean]

In [4]:
%sql
use schema sql_challenges;
show tables

DataFrame[database: string, tableName: string, isTemporary: boolean]

In [7]:
fs ls /

PermissionDenied: Public DBFS root is disabled. Access is denied on path: /. Config: host=https://dbc-cdd467ab-cdba.cloud.databricks.com, account_id=b449a46a-3482-42aa-b445-03310d266f0d, workspace_id=2588661780433101, discovery_url=https://dbc-cdd467ab-cdba.cloud.databricks.com/oidc/.well-known/oauth-authorization-server, token_audience=https://dbc-cdd467ab-cdba.cloud.databricks.com/oidc/v1/token, auth_type=metadata-service, serverless_compute_id=auto, metadata_service_url=***. Env: DATABRICKS_HOST, DATABRICKS_AUTH_TYPE, DATABRICKS_SERVERLESS_COMPUTE_ID, DATABRICKS_METADATA_SERVICE_URL